[package]
name = "n_test"
version = "0.1.0"
authors = ["boris"]

[dependencies]
rand = "0.6"
ndarray = "0.12"
ndarray-linalg = { version = "0.10", features=['openblas'] }
openblas-src = { version = "0.7.0" }
# intel-mkl-src = "0.4"
